name = "fintune"
main= "src/index.tsx"
compatibility_date = "2023-01-01"
account_id = "a1ff2aa041f76f9625bfe6f7a9ba2923"

[site]
bucket = "./assets"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "fintune"
database_id = "dcb1c4b2-d194-44bb-adc2-a1085b8c495f"
